platform :ios, '13.0'
use_frameworks!

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

def appodeal_pods
  # pod 'APDAmazonAdsAdapter', '2.11.0.1'
  pod 'APDAppLovinAdapter', '2.11.0.1'
  pod 'APDBidMachineAdapter', '2.11.0.1' # Required
  # pod 'APDFacebookAudienceAdapter', '2.11.0.1'
  pod 'APDIronSourceAdapter', '2.11.0.1'
  pod 'APDMyTargetAdapter', '2.11.0.1'
  pod 'APDOguryAdapter', '2.11.0.1'
  pod 'APDUnityAdapter', '2.11.0.1'
  pod 'APDYandexAdapter', '2.11.0.1'
end

target 'Plugin' do
  capacitor_pods
  appodeal_pods
end

target 'PluginTests' do
  capacitor_pods
end
